CREATE TABLE IF NOT EXISTS quests (
	id BIGINT AUTO_INCREMENT,
	userId VARCHAR(255) NOT NULL,
	questType VARCHAR(255) NOT NULL,
	questId VARCHAR(255) NOT NULL,
	progress INT NOT NULL DEFAULT 0,
	progressGoal INT DEFAULT NULL,
	itemReward VARCHAR(255) DEFAULT NULL,
	xpReward INT DEFAULT NULL,
	moneyReward INT DEFAULT NULL,
	createdAt DATETIME NOT NULL DEFAULT NOW(),
	KEY (userId),
	PRIMARY KEY (id)
) ENGINE = InnoDB;

ALTER TABLE quests AUTO_INCREMENT = 1000;
