CREATE TABLE IF NOT EXISTS shop_items (
	itemId BIGINT NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT NOW(),
	price INT NOT NULL,
	PRIMARY KEY (itemId),
	FOREIGN KEY (itemId) REFERENCES items (id) ON DELETE CASCADE
) ENGINE = InnoDB;
