ALTER TABLE users ADD COLUMN kills INT NOT NULL DEFAULT 0 AFTER shopSales;
ALTER TABLE users ADD COLUMN deaths INT NOT NULL DEFAULT 0 AFTER kills;
ALTER TABLE users ADD COLUMN npckills INT NOT NULL DEFAULT 0 AFTER deaths;
ALTER TABLE users ADD COLUMN bossKills INT NOT NULL DEFAULT 0 AFTER npckills;
