CREATE TABLE IF NOT EXISTS npcs (
	channelId VARCHAR(255) NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT NOW(),
	health INT NOT NULL,
	id VARCHAR(255) NOT NULL,
	PRIMARY KEY (channelId)
) ENGINE = InnoDB;
