CREATE TABLE IF NOT EXISTS skins (
	id BIGINT AUTO_INCREMENT,
	userId VARCHAR(255) NOT NULL,
	skin VARCHAR(255) NOT NULL,
	skinCreatedAt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id),
	KEY (userId)
) ENGINE = InnoDB;

ALTER TABLE skins AUTO_INCREMENT = 10000;

ALTER TABLE items ADD COLUMN skin VARCHAR(255) DEFAULT NULL AFTER displayName;
