ALTER TABLE items ADD COLUMN itemCreatedAt DATETIME NOT NULL DEFAULT NOW() AFTER displayName;

CREATE TABLE IF NOT EXISTS attachment_items (
	itemId BIGINT NOT NULL,
	weaponId BIGINT NOT NULL,
	PRIMARY KEY (itemId),
	FOREIGN KEY (itemId) REFERENCES items (id) ON DELETE CASCADE,
	FOREIGN KEY (weaponId) REFERENCES items (id) ON DELETE CASCADE
) ENGINE = InnoDB;
