DROP TABLE IF EXISTS quests;

CREATE TABLE IF NOT EXISTS quests (
	userId VARCHAR(255) NOT NULL,
	questType VARCHAR(255) NOT NULL,
	questId VARCHAR(255) NOT NULL,
	progress INT NOT NULL DEFAULT 0,
	progressGoal INT DEFAULT NULL,
	itemReward VARCHAR(255) DEFAULT NULL,
	xpReward INT NOT NULL,
	moneyReward INT DEFAULT NULL,
	createdAt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (userId)
) ENGINE = InnoDB;

