import { Medical } from '../../types/Items'

const medicalObject = <T>(et: { [K in keyof T]: Medical & { name: K } }) => et

export const medical = medicalObject({
	'bandage': {
		type: 'Medical',
		name: 'bandage',
		icon: '<:medical:886561670745452554>',
		aliases: ['bandage'],
		sellPrice: 37,
		healsFor: 20,
		slotsUsed: 1,
		speed: 25,
		itemLevel: 1,
		durability: 2,
		curesBitten: false,
		curesBrokenArm: false,
		curesBurning: false
	},
	'ifak_medkit': {
		type: 'Medical',
		name: 'ifak_medkit',
		icon: '<:medical:886561670745452554>',
		aliases: ['ifak', 'medkit'],
		description: 'An individual first aid kit which contains supplies for immediate minor injuries.',
		sellPrice: 102,
		healsFor: 25,
		slotsUsed: 2,
		speed: 6,
		itemLevel: 3,
		durability: 4,
		curesBitten: false,
		curesBrokenArm: false,
		curesBurning: false
	},
	'compression_bandage': {
		type: 'Medical',
		name: 'compression_bandage',
		icon: '<:medical:886561670745452554>',
		description: 'Elastic bandage designed to reduce the flow of blood to an area in order to restrict swelling.',
		aliases: ['compress_bandage', 'compress'],
		sellPrice: 152,
		healsFor: 20,
		slotsUsed: 1,
		speed: 20,
		itemLevel: 3,
		durability: 2,
		curesBitten: false,
		curesBrokenArm: false,
		curesBurning: false
	},
	'hyfin_chest_seal': {
		type: 'Medical',
		name: 'hyfin_chest_seal',
		icon: '<:medical:886561670745452554>',
		aliases: ['chest_seal', 'hyfin', 'hyfin_seal', 'seal'],
		description: 'Compact chest seal designed to seal penetrative wounds to the chest.',
		sellPrice: 1202,
		healsFor: 62,
		slotsUsed: 1,
		itemLevel: 9,
		durability: 4,
		curesBitten: false,
		curesBrokenArm: false,
		curesBurning: false,
		speed: 3
	},
	'paracetamol': {
		type: 'Medical',
		name: 'paracetamol',
		icon: '<:U_usable:601366669259964418>',
		aliases: ['paracet'],
		sellPrice: 429,
		healsFor: 35,
		slotsUsed: 1,
		itemLevel: 4,
		durability: 3,
		curesBitten: false,
		curesBrokenArm: false,
		curesBurning: false,
		speed: 10
	},
	'splint': {
		type: 'Medical',
		name: 'splint',
		icon: '<:U_usable:601366669259964418>',
		description: 'Use this to fix broken limbs.',
		aliases: [],
		sellPrice: 146,
		healsFor: 10,
		slotsUsed: 1,
		itemLevel: 1,
		durability: 1,
		curesBitten: false,
		curesBrokenArm: true,
		curesBurning: false,
		speed: 15
	},
	'anti-biotics': {
		type: 'Medical',
		name: 'anti-biotics',
		icon: '<:U_usable:601366669259964418>',
		description: 'Cures various infections, such as those from walker bites.',
		aliases: ['antibiotics'],
		sellPrice: 307,
		healsFor: 20,
		slotsUsed: 1,
		itemLevel: 3,
		durability: 1,
		curesBitten: true,
		curesBrokenArm: false,
		curesBurning: false,
		speed: 20
	}
})
